/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import dao.Dao_KhuyenMai;
import entity.KhuyenMai;
import entity.NhanVien;
import entity.TaiKhoan;

/**
 *
 * @author ACER
 */
public class FrmDiscount extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private Dao_KhuyenMai khuyenMai_dao = new Dao_KhuyenMai();
    private DefaultTableModel modelKM;
    
    public FrmDiscount() {
        initComponents();
        modelKM = (DefaultTableModel) tblKhuyenMai.getModel();
        napDuLieuTuCSDL(khuyenMai_dao.getAllKhuyenMai());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbTinhTrang = new javax.swing.JComboBox<>();
        jdNgayBatDau = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jdNgayKetThuc = new com.toedter.calendar.JDateChooser();
        cbDoiTuong = new javax.swing.JComboBox<>();
        txtGiamGia = new javax.swing.JTextField();
        txtMess = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTaoMoi = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khuyến mãi"));

        jLabel3.setText("Mã khuyến mãi:");

        jLabel4.setText("Tên khuyến mãi:");

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        jLabel5.setText("Giá trị giảm giá:");

        jLabel8.setText("Ngày bắt đầu:");

        jLabel10.setText("Tình trạng:");

        cbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang diễn ra", "Sắp diễn ra", "Đã kết thúc" }));
        cbTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTinhTrangActionPerformed(evt);
            }
        });

        jdNgayBatDau.setDateFormatString("yyyy-MM-dd");

        jLabel11.setText("Ngày kết thúc:");

        jLabel12.setText("Đối tượng áp dụng:");

        jdNgayKetThuc.setDateFormatString("yyyy-MM-dd");

        cbDoiTuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Khách hàng mới", "Khách hàng tiềm năng" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel12))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jdNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel11)
                                .addGap(34, 34, 34)
                                .addComponent(jdNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtMess, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDoiTuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTinhTrang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jdNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(cbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 150));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update2.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnTaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat)
                .addGap(18, 18, 18)
                .addComponent(btnTaoMoi)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnTaoMoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm khuyến mãi"));

        jLabel7.setText("Nhập tên khuyến mãi:");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1190, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khuyến mãi"));

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Giá trị giảm giá", "Ngày bắt đầu", "Ngày kết thúc", "Đối tượng áp dụng", "Tình trạng"
            }
        ));
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1190, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {
        KhuyenMai km = revertKhuyenMaiFromFields();
        if(!khuyenMai_dao.them(km)) {
        	System.out.println(km);
        	JOptionPane.showMessageDialog(this, "Thêm thất bại. Đã xảy ra lỗi!!!");
        	
        }else {
        	napDuLieuTuCSDL(khuyenMai_dao.getAllKhuyenMai());
        	tblKhuyenMai.clearSelection();
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        update();
    }

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        xoaTrang();
        napDuLieuTuCSDL(khuyenMai_dao.getAllKhuyenMai());
        tblKhuyenMai.clearSelection();
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
        timKMTheoTen();
        
    }

    private void cbTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTinhTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTinhTrangActionPerformed

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {
        int r = tblKhuyenMai.getSelectedRow();
        fillForm(r);
    }
    
    public void napDuLieuTuCSDL(ArrayList<KhuyenMai> ds) {
    	DefaultTableModel dm = (DefaultTableModel) tblKhuyenMai.getModel();
		dm.getDataVector().removeAllElements();
		for (KhuyenMai km : ds) {
			modelKM.addRow(new Object[] {km.getMaKhuyenMai(),km.getTenKhuyenMai(),km.getGiaTriGiamGia(),km.getNgayBatDau(),km.getNgayKetThuc(),km.getDoiTuongApDung(),km.getTinhTrang()});
		}
    }
    
    private void xoaTrang() {
    	txtMa.setText("");
    	txtTen.setText("");
    	txtGiamGia.setText("");
    	jdNgayBatDau.setCalendar(null);
    	jdNgayKetThuc.setCalendar(null);
    	cbDoiTuong.setSelectedIndex(0);
    	cbTinhTrang.setSelectedIndex(0);
    }
    
    private boolean validDate() {
    	String tenKM = txtTen.getText().trim();
//    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//    	String ngayBatDau = sdf.format(jdNgayBatDau.getDate());
//    	String ngayKetThuc = sdf.format(jdNgayKetThuc.getDate());
    	String doiTuongApDung = cbDoiTuong.getSelectedItem().toString();
    	String tinhTrang = cbTinhTrang.getSelectedItem().toString();
    	
    	if(tenKM.equals("")) {
    		txtMess.setText("Tên khuyến mãi không được để trống!!!");
    		return false;
    	}
    	else if(doiTuongApDung.equals("")) {
    		txtMess.setText("Đối tượng áp dụng không được để trống!!!");
    		return false;
    	}
    	if(tinhTrang.equals("")) {
    		txtMess.setText("Tình trạng không được để trống!!!");
    		return false;
    	}
    	
    	return true;
    }
    
    private KhuyenMai revertKhuyenMaiFromFields() {
    	String maKM = phatSinhMaKM();
    	String tenKM = txtTen.getText().trim();
    	int giamGia = Integer.parseInt(txtGiamGia.getText().trim());
    	java.util.Date utilNgayBatDau = jdNgayBatDau.getDate();
        java.sql.Date ngayBatDau = new java.sql.Date(utilNgayBatDau.getTime());
        java.util.Date utilNgayKetThuc = jdNgayKetThuc.getDate();
        java.sql.Date ngayKetThuc = new java.sql.Date(utilNgayKetThuc.getTime());
    	String doiTuongApDung = cbDoiTuong.getSelectedItem().toString();
    	String tinhTrang = cbTinhTrang.getSelectedItem().toString();
    	KhuyenMai km = new KhuyenMai(maKM, tenKM, giamGia, ngayBatDau, ngayKetThuc, doiTuongApDung, tinhTrang);
    	return km;
    }
    
    public String phatSinhMaKM() {
    	String prefix = "KM";
    	return prefix + String.format("%03d", modelKM.getRowCount()+ 1);
    }
    
    
    private void update() {
    	int r = tblKhuyenMai.getSelectedRow();
		if (r == -1) {
			JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng để cập nhật thông tin");
		} else {
			String maKM = txtMa.getText().trim();
			String tenKM = txtTen.getText().trim();
			int giamGia = Integer.parseInt(txtGiamGia.getText().trim());
	    	java.util.Date utilNgayBatDau = jdNgayBatDau.getDate();
	        java.sql.Date ngayBatDau = new java.sql.Date(utilNgayBatDau.getTime());
	        java.util.Date utilNgayKetThuc = jdNgayKetThuc.getDate();
	        java.sql.Date ngayKetThuc = new java.sql.Date(utilNgayKetThuc.getTime());
	    	String doiTuongApDung = cbDoiTuong.getSelectedItem().toString();
	    	String tinhTrang = cbTinhTrang.getSelectedItem().toString();
	    	KhuyenMai kmMoi = new KhuyenMai(maKM, tenKM, giamGia, ngayBatDau, ngayKetThuc, doiTuongApDung, tinhTrang);
			if (!khuyenMai_dao.capNhat(kmMoi)) {
				JOptionPane.showMessageDialog(this, "Lỗi không thể cập nhật");
				tblKhuyenMai.clearSelection();
			} else {
				JOptionPane.showMessageDialog(this, "Cập nhật thành công");
				napDuLieuTuCSDL(khuyenMai_dao.getAllKhuyenMai());
			}
		}
    }
    
    public void fillForm(int r) {
    	txtMa.setText(tblKhuyenMai.getValueAt(r, 0).toString());
    	txtTen.setText(tblKhuyenMai.getValueAt(r, 1).toString());
    	txtGiamGia.setText(tblKhuyenMai.getValueAt(r, 2).toString());
    	jdNgayBatDau.setDate((java.util.Date) tblKhuyenMai.getValueAt(r, 3));
    	jdNgayKetThuc.setDate((java.util.Date) tblKhuyenMai.getValueAt(r, 4));
    	cbDoiTuong.setSelectedItem(tblKhuyenMai.getValueAt(r, 5).toString());
    	cbTinhTrang.setSelectedItem(tblKhuyenMai.getValueAt(r, 6).toString());
    }
    
    public void timKMTheoTen() {
    	String ten = txtTimKiem.getText().trim();
    	if (ten.trim() == "") {
			napDuLieuTuCSDL(khuyenMai_dao.getAllKhuyenMai());
			xoaTrang();
		} else {
			ArrayList<KhuyenMai> kmList = khuyenMai_dao.getKhuyenMaiTheoTen(ten);
			if (kmList.size() > 0) {
				napDuLieuTuCSDL(kmList);
				xoaTrang();

			} else {
				JOptionPane.showMessageDialog(this, "Không tìm thấy!");
			}
		}
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbDoiTuong;
    private javax.swing.JComboBox<String> cbTinhTrang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdNgayBatDau;
    private com.toedter.calendar.JDateChooser jdNgayKetThuc;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMess;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
