/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;



/**
 *
 * @author ACER
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    Color DefaultColor,ClickColor;
    
    public FrmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultColor = new Color(13,36,51);
        ClickColor = new Color(240,151,57);
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);        
        



        
                
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        DPAccount = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblSell = new javax.swing.JLabel();
        lblBuy = new javax.swing.JLabel();
        DPOrder = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblCustomer = new javax.swing.JLabel();
        lblStaff = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblOrder = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblWarehouse = new javax.swing.JLabel();
        DPManage = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblCustomerSta = new javax.swing.JLabel();
        lblProductSta = new javax.swing.JLabel();
        lblOrderSta = new javax.swing.JLabel();
        lblRevenueSta = new javax.swing.JLabel();
        lblWarehouseSta = new javax.swing.JLabel();
        DPSta = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info48.png"))); // NOI18N
        lblInfo.setText("Xem thông tin");
        lblInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblInfoMousePressed(evt);
            }
        });

        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign_out.png"))); // NOI18N
        lblLogout.setText("Đăng xuất");
        lblLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLogoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1034, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogout)
                    .addComponent(lblInfo))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        DPAccount.setBackground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout DPAccountLayout = new javax.swing.GroupLayout(DPAccount);
        DPAccount.setLayout(DPAccountLayout);
        DPAccountLayout.setHorizontalGroup(
            DPAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DPAccountLayout.setVerticalGroup(
            DPAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DPAccount)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DPAccount))
        );

        jTabbedPane1.addTab("Tài khoản", jPanel2);

        lblSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order.png"))); // NOI18N
        lblSell.setText("Bán hàng");
        lblSell.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSell.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSellMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSellMousePressed(evt);
            }
        });

        lblBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buy.png"))); // NOI18N
        lblBuy.setText("Nhập hàng");
        lblBuy.setToolTipText("");
        lblBuy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBuy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBuyMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblSell, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBuy)
                .addContainerGap(1049, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DPOrderLayout = new javax.swing.GroupLayout(DPOrder);
        DPOrder.setLayout(DPOrderLayout);
        DPOrderLayout.setHorizontalGroup(
            DPOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DPOrderLayout.setVerticalGroup(
            DPOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DPOrder)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DPOrder))
        );

        jTabbedPane1.addTab("Giao dịch", jPanel3);

        lblCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer (2).png"))); // NOI18N
        lblCustomer.setText("Khách hàng");
        lblCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCustomerMousePressed(evt);
            }
        });

        lblStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer.png"))); // NOI18N
        lblStaff.setText("Nhân viên");
        lblStaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblStaff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStaffMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblStaffMousePressed(evt);
            }
        });

        lblProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product.png"))); // NOI18N
        lblProduct.setText("Sản phẩm");
        lblProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblProductMousePressed(evt);
            }
        });

        lblOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order.png"))); // NOI18N
        lblOrder.setText("Hóa đơn");
        lblOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblOrder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOrderMousePressed(evt);
            }
        });

        lblDiscount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sale.png"))); // NOI18N
        lblDiscount.setText("Khuyến mãi");
        lblDiscount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDiscount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblDiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDiscountMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDiscountMousePressed(evt);
            }
        });

        lblSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supplier.png"))); // NOI18N
        lblSupplier.setText("Nhà cung cấp");
        lblSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSupplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSupplierMousePressed(evt);
            }
        });

        lblWarehouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        lblWarehouse.setText("Kho hàng");
        lblWarehouse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblWarehouse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStaff)
                .addGap(12, 12, 12)
                .addComponent(lblProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDiscount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWarehouse)
                .addContainerGap(700, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDiscount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWarehouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DPManageLayout = new javax.swing.GroupLayout(DPManage);
        DPManage.setLayout(DPManageLayout);
        DPManageLayout.setHorizontalGroup(
            DPManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DPManageLayout.setVerticalGroup(
            DPManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DPManage)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DPManage))
        );

        jTabbedPane1.addTab("Quản lý", jPanel4);

        lblCustomerSta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer (2).png"))); // NOI18N
        lblCustomerSta.setText("Khách hàng");
        lblCustomerSta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCustomerSta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblProductSta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product.png"))); // NOI18N
        lblProductSta.setText("Sản phẩm");
        lblProductSta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProductSta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblOrderSta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order.png"))); // NOI18N
        lblOrderSta.setText("Hóa đơn");
        lblOrderSta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblOrderSta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblRevenueSta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        lblRevenueSta.setText("Doanh thu");
        lblRevenueSta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRevenueSta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblWarehouseSta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        lblWarehouseSta.setText("Tồn kho");
        lblWarehouseSta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblWarehouseSta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblWarehouseSta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCustomerSta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProductSta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOrderSta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRevenueSta)
                .addContainerGap(858, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCustomerSta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblOrderSta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProductSta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRevenueSta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWarehouseSta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DPStaLayout = new javax.swing.GroupLayout(DPSta);
        DPSta.setLayout(DPStaLayout);
        DPStaLayout.setHorizontalGroup(
            DPStaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DPStaLayout.setVerticalGroup(
            DPStaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DPSta)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DPSta))
        );

        jTabbedPane1.addTab("Thống kê", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Trợ giúp", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoMouseClicked
        FrmInfo info = new FrmInfo();
        DPAccount.removeAll();
        DPAccount.add(info).setVisible(true);
    }//GEN-LAST:event_lblInfoMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        FrmLogout logout = new FrmLogout();
        DPAccount.removeAll();
        DPAccount.add(logout).setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellMouseClicked
        FrmSell sell = new FrmSell();
        DPOrder.removeAll();
        DPOrder.add(sell).setVisible(true);
    }//GEN-LAST:event_lblSellMouseClicked

    private void lblBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuyMouseClicked
        FrmBuy buy = new FrmBuy();
        DPOrder.removeAll();
        DPOrder.add(buy).setVisible(true);
    }//GEN-LAST:event_lblBuyMouseClicked

    private void lblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseClicked
        FrmCustomer customer = new FrmCustomer();
        DPManage.removeAll();
        DPManage.add(customer).setVisible(true);
    }//GEN-LAST:event_lblCustomerMouseClicked

    private void lblStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStaffMouseClicked
        FrmStaff staff = new FrmStaff();
        DPManage.removeAll();
        DPManage.add(staff).setVisible(true);
    }//GEN-LAST:event_lblStaffMouseClicked

    private void lblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrderMouseClicked
        FrmOrder order = new FrmOrder();
        DPManage.removeAll();
        DPManage.add(order).setVisible(true);
    }//GEN-LAST:event_lblOrderMouseClicked

    private void lblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseClicked
        FrmProduct product = new FrmProduct();
        DPManage.removeAll();
        DPManage.add(product).setVisible(true);
    }//GEN-LAST:event_lblProductMouseClicked

    private void lblInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoMousePressed
        lblInfo.setForeground(ClickColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);  
    }//GEN-LAST:event_lblInfoMousePressed

    private void lblLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMousePressed
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(ClickColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);  
    }//GEN-LAST:event_lblLogoutMousePressed

    private void lblSellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellMousePressed
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(ClickColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);  
    }//GEN-LAST:event_lblSellMousePressed

    private void lblBuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuyMousePressed
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(ClickColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);  
    }//GEN-LAST:event_lblBuyMousePressed

    private void lblCustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMousePressed
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(ClickColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);      
    }//GEN-LAST:event_lblCustomerMousePressed

    private void lblStaffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStaffMousePressed
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(ClickColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);      
    }//GEN-LAST:event_lblStaffMousePressed

    private void lblProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMousePressed
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(ClickColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);      
    }//GEN-LAST:event_lblProductMousePressed

    private void lblOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrderMousePressed
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(ClickColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);      
    }//GEN-LAST:event_lblOrderMousePressed

    private void lblDiscountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiscountMouseClicked
        FrmDiscount discount = new FrmDiscount();
        DPManage.removeAll();
        DPManage.add(discount).setVisible(true);
    }//GEN-LAST:event_lblDiscountMouseClicked

    private void lblDiscountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiscountMousePressed
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(ClickColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(DefaultColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);    
    }//GEN-LAST:event_lblDiscountMousePressed

    private void lblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseClicked
        FrmSupplier supplier = new FrmSupplier();
        DPManage.removeAll();
        DPManage.add(supplier).setVisible(true);
    }//GEN-LAST:event_lblSupplierMouseClicked

    private void lblSupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMousePressed
        lblInfo.setForeground(DefaultColor);
        lblLogout.setForeground(DefaultColor);
        lblSell.setForeground(DefaultColor);        
        lblBuy.setForeground(DefaultColor);
        lblCustomer.setForeground(DefaultColor);
        lblCustomerSta.setForeground(DefaultColor);
        lblDiscount.setForeground(DefaultColor);
        lblOrder.setForeground(DefaultColor);
        lblOrderSta.setForeground(DefaultColor);
        lblProduct.setForeground(DefaultColor);
        lblProductSta.setForeground(DefaultColor);
        lblRevenueSta.setForeground(DefaultColor);        
        lblStaff.setForeground(DefaultColor);
        lblSupplier.setForeground(ClickColor);
        lblWarehouse.setForeground(DefaultColor);
        lblWarehouseSta.setForeground(DefaultColor);  
    }//GEN-LAST:event_lblSupplierMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DPAccount;
    private javax.swing.JDesktopPane DPManage;
    private javax.swing.JDesktopPane DPOrder;
    private javax.swing.JDesktopPane DPSta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBuy;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblCustomerSta;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrderSta;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProductSta;
    private javax.swing.JLabel lblRevenueSta;
    private javax.swing.JLabel lblSell;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblWarehouse;
    private javax.swing.JLabel lblWarehouseSta;
    // End of variables declaration//GEN-END:variables
}
