/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import dao.Dao_NhanVien;
import dao.Dao_TaiKhoan;
import entity.NhanVien;
import entity.TaiKhoan;

/**
 *
 * @author ACER
 */
public class FrmStaff extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private Dao_NhanVien nhanVien_dao = new Dao_NhanVien();
    private Dao_TaiKhoan taiKhoan_dao = new Dao_TaiKhoan();
    private DefaultTableModel modelNV;
    private DefaultTableModel modelTK;
    
	/**
     * Creates new form FrmStaff
     */
    public FrmStaff() {
        initComponents();
        modelNV= (DefaultTableModel) tblNhanVien.getModel();
        modelTK= (DefaultTableModel) tblTaiKhoan.getModel();
        napDuLieuNhanVienTuCSDL(nhanVien_dao.getAllNhanVien());
        napDuLieuTaiKhoanTuCSDL(taiKhoan_dao.getAllTaiKhoan());
        napComboBoxMaNhanVien(nhanVien_dao.getAllNhanVien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tpNhanVien = new javax.swing.JTabbedPane();
        pnlNhanVien = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHoTenNhanVien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        cbChucVu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbTinhTrang = new javax.swing.JComboBox<>();
        txtMessage = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTaoMoi = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        pnlTaiKhoan = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtMaTK = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmailTK = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbMaNhanVien = new javax.swing.JComboBox<>();
        txtMessageTK = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btnThemTK = new javax.swing.JButton();
        btnCapNhatTK = new javax.swing.JButton();
        btnTaoMoiTK = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtTimTK = new javax.swing.JTextField();
        btnTimTK = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        jLabel1.setText("Mã nhân viên:");

        txtMaNhanVien.setEnabled(false);
        txtMaNhanVien.setFocusable(false);

        jLabel2.setText("Họ tên:");

        txtHoTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenNhanVienActionPerformed(evt);
            }
        });

        jLabel3.setText("Ngày sinh:");

        jdNgaySinh.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Địa chỉ:");

        jLabel5.setText("Số điện thoại:");

        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });

        jLabel6.setText("Email:");

        jLabel7.setText("Giới tính:");

        btnGroup.add(rdNam);
        rdNam.setText("Nam");
        rdNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNamActionPerformed(evt);
            }
        });

        btnGroup.add(rdNu);
        rdNu.setText("Nữ");
        rdNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNuActionPerformed(evt);
            }
        });

        jLabel8.setText("Chức vụ:");

        cbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên bán hàng", "Nhân viên quản lý", " " }));
        cbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChucVuActionPerformed(evt);
            }
        });

        jLabel9.setText("Tình trạng:");

        cbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm việc", "Tạm ngưng", " " }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMessage)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoDienThoai))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jdNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiaChi))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdNu)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTinhTrang, 0, 186, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jdNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHoTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txtSoDienThoai)
                    .addComponent(rdNam)
                    .addComponent(cbChucVu)
                    .addComponent(cbTinhTrang)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail)
                    .addComponent(rdNu)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 150));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update2.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnTaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat)
                .addGap(18, 18, 18)
                .addComponent(btnTaoMoi)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnTaoMoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm nhân viên"));

        jLabel10.setText("Nhập số điện thoại hoặc họ tên:");

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1190, 110));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhân viên"));
        jPanel9.setPreferredSize(new java.awt.Dimension(1190, 300));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Ngày sinh", "Địa chỉ", "Số điện thoại", "Email", "Giới tính", "Tình trạng", "Chức vụ"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1190, 330));

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpNhanVien.addTab("Nhân viên", pnlNhanVien);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin tài khoản"));

        jLabel11.setText("Mã tài khoản:");

        txtMaTK.setEnabled(false);
        txtMaTK.setFocusable(false);

        jLabel12.setText("Email:");

        jLabel13.setText("Mật khẩu:");

        jLabel14.setText("Tên tài khoản:");

        jLabel15.setText("Mã nhân viên:");

        cbMaNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaTK)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addGap(41, 41, 41)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(cbMaNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtEmailTK, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(51, 51, 51)
                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMessageTK))
                .addGap(48, 48, 48))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmailTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(cbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMessageTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 130));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnThemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnThemTK.setText("Thêm");
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });

        btnCapNhatTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update2.png"))); // NOI18N
        btnCapNhatTK.setText("Cập nhật");
        btnCapNhatTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTKActionPerformed(evt);
            }
        });

        btnTaoMoiTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnTaoMoiTK.setText("Tạo mới");
        btnTaoMoiTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemTK)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhatTK)
                .addGap(18, 18, 18)
                .addComponent(btnTaoMoiTK)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTK)
                    .addComponent(btnCapNhatTK)
                    .addComponent(btnTaoMoiTK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm tài khoản"));

        jLabel20.setText("Nhập email nhân viên:");

        btnTimTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        btnTimTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtTimTK, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTimTK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTimTK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1190, 120));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách tài khoản"));
        jPanel15.setPreferredSize(new java.awt.Dimension(1190, 300));

        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã tài khoản", "Email", "Mật khẩu", "Tên tài khoản", "Mã nhân viên"
            }
        ));
        tblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTaiKhoan);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1190, 330));

        javax.swing.GroupLayout pnlTaiKhoanLayout = new javax.swing.GroupLayout(pnlTaiKhoan);
        pnlTaiKhoan.setLayout(pnlTaiKhoanLayout);
        pnlTaiKhoanLayout.setHorizontalGroup(
            pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTaiKhoanLayout.setVerticalGroup(
            pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpNhanVien.addTab("Tài khoản nhân viên", pnlTaiKhoan);

        jPanel1.add(tpNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {
    	if (validDate()) {
			NhanVien nv = revertNhanVienFromFields();
			System.out.println(nv);
			if (!nhanVien_dao.them(nv)) {
				JOptionPane.showMessageDialog(this, "Thêm thất bại. Đã xảy ra lỗi!!!");
			} else {
				napDuLieuNhanVienTuCSDL(nhanVien_dao.getAllNhanVien());
				tblNhanVien.clearSelection();

			}
		}
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        update();
        napDuLieuNhanVienTuCSDL(nhanVien_dao.getAllNhanVien());
    }

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {
        xoaTrangNhanVien();
        napDuLieuNhanVienTuCSDL(nhanVien_dao.getAllNhanVien());
        tblNhanVien.clearSelection();
    }

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {
        timTheoSDT();
//        System.out.println(modelNV.getRowCount());
    }

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {
    	TaiKhoan tk = revertTaiKhoanFromFields();
		System.out.println(tk);
		if (!taiKhoan_dao.them(tk)) {
			JOptionPane.showMessageDialog(this, "Thêm thất bại. Đã xảy ra lỗi!!!");
		} else {
			napDuLieuTaiKhoanTuCSDL(taiKhoan_dao.getAllTaiKhoan());
			tblTaiKhoan.clearSelection();

		}
    }

    private void btnCapNhatTKActionPerformed(java.awt.event.ActionEvent evt) {
        updateTaiKhoan();
    }

    private void btnTaoMoiTKActionPerformed(java.awt.event.ActionEvent evt) {
        xoaTrangTaiKhoan();
        napDuLieuTaiKhoanTuCSDL(taiKhoan_dao.getAllTaiKhoan());
        tblTaiKhoan.clearSelection();
    }                                           

    private void btnTimTKActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	String email = txtTimTK.getText().trim();
		TaiKhoan tk = taiKhoan_dao.getTKTheoEmail(email);
		if (tk != null) {
			DefaultTableModel dm = (DefaultTableModel) tblTaiKhoan.getModel();
			dm.getDataVector().removeAllElements();
			modelTK.addRow(new Object[] {tk.getMaTaiKhoan(),tk.getEmail(),tk.getMatKhau(),tk.getTenTaiKhoan(),tk.getNhanVien().getMaNhanVien()});
		} else {
			JOptionPane.showMessageDialog(this, "Không tìm thấy!");
		}
		xoaTrangTaiKhoan();
    }

    private void txtHoTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenNhanVienActionPerformed

    private void cbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChucVuActionPerformed

    private void rdNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNuActionPerformed

    private void rdNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNamActionPerformed


    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void txtTenTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTaiKhoanActionPerformed

    private void tblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {
        int r = tblTaiKhoan.getSelectedRow();
        fillFormTK(r);
    }

    private void cbMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {
    	// TODO add your handling code here:
    }

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {
        int r = tblNhanVien.getSelectedRow();
        fillForm(r);
    }

    public void napDuLieuNhanVienTuCSDL(ArrayList<NhanVien> ds) {
    	DefaultTableModel dm = (DefaultTableModel) tblNhanVien.getModel();
		dm.getDataVector().removeAllElements();
		for (NhanVien nv : ds) {
			modelNV.addRow(new Object[] { nv.getMaNhanVien(), nv.getHoTenNhanVien(),nv.getNgaySinh(), nv.getDiaChi(), nv.getSoDienThoai(),
					nv.getEmail(), nv.isGioiTinh() ? "Nam" : "Nữ" ,nv.getTinhTrang(), nv.getChucVu()});
		}
    }
    
    
    
    
    private void xoaTrangNhanVien() {
		txtMaNhanVien.setText("");
		txtHoTenNhanVien.setText("");
		jdNgaySinh.setCalendar(null);
		txtDiaChi.setText("");
		txtSoDienThoai.setText("");
		txtEmail.setText("");
		rdNam.setSelected(true);
		cbChucVu.setSelectedIndex(0);
		cbTinhTrang.setSelectedIndex(0);
	}
    
    private boolean validDate() {
    	String hoTen = txtHoTenNhanVien.getText().trim();
    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    	String ngaySinh = sdf.format(jdNgaySinh.getDate());
    	String diaChi = txtDiaChi.getText().trim();
    	String soDienThoai = txtSoDienThoai.getText().trim();
//    	String email = txtEmail.getText().trim();
    	
    	if(hoTen.equals("")) {
    		txtMessage.setText("Họ tên nhân viên không được để trống!!!");
    		return false;
    	}
    	if(ngaySinh.equals("")) {
    		txtMessage.setText("Bạn hãy chọn ngày sinh cho nhân viên!!!");
    		return false;
    	}
    	if(diaChi.equals("")) {
    		txtMessage.setText("Địa chỉ không được để trống!!!");
    		return false;
    	}
    	if (!soDienThoai.matches("^0\\d{9}")) {
			txtMessage.setText("Số điện thoại phải bắt đầu bằng 0 và có tổng cộng 10 số");
			return false;
		}
//		if (!email.matches(
//			"^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$")) {
//			txtMessage.setText("Email sai cú pháp!!!");
//			return false;
//		}
		return true;
    }
    
    private NhanVien revertNhanVienFromFields() {
    	String maNV ="";
    	String hoTen = txtHoTenNhanVien.getText().trim();
    	java.util.Date utilNgaySinh = jdNgaySinh.getDate();
        java.sql.Date ngaySinh = new java.sql.Date(utilNgaySinh.getTime());
    	String diaChi = txtDiaChi.getText().trim();
    	String sdt = txtSoDienThoai.getText().trim();
    	String email = txtEmail.getText().trim();
    	boolean gioiTinh = rdNam.isSelected();
    	String chucVu = (String) cbChucVu.getSelectedItem();
    	String tinhTrang = (String) cbTinhTrang.getSelectedItem();
    	maNV = phatSinhMaNV(chucVu);
    	NhanVien nv = new NhanVien(maNV, hoTen, ngaySinh, diaChi, sdt, email, gioiTinh, tinhTrang, chucVu);
		return nv;
    }
    
    private void update() {
    	int r = tblNhanVien.getSelectedRow();
		if (r == -1) {
			JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng để cập nhật thông tin");
		} else {
			if (validDate()) {
				NhanVien nvMoi = revertNhanVienFromFields();
				if (!nhanVien_dao.capNhat(nvMoi)) {
					System.out.println(nvMoi);
					JOptionPane.showMessageDialog(this, "Lỗi không thể cập nhật");
					tblNhanVien.clearSelection();
				} else {
					
					JOptionPane.showMessageDialog(this, "Cập nhật thành công");
				}
			}
		}
    }
    
    public void fillForm(int r) {
		txtMaNhanVien.setEditable(false);
		txtMaNhanVien.setText(tblNhanVien.getValueAt(r, 0).toString());
		txtHoTenNhanVien.setText(tblNhanVien.getValueAt(r, 1).toString());
		jdNgaySinh.setDate((java.util.Date) tblNhanVien.getValueAt(r, 2));
		txtDiaChi.setText(tblNhanVien.getValueAt(r, 3).toString());
		txtSoDienThoai.setText(tblNhanVien.getValueAt(r, 4).toString());
		txtEmail.setText(tblNhanVien.getValueAt(r, 5).toString());
		String gt = tblNhanVien.getValueAt(r, 6).toString();
		if (gt.equals("Nam")) {
			rdNam.setSelected(true);
		} else {
			rdNu.setSelected(true);
		}
		cbChucVu.setSelectedItem(tblNhanVien.getValueAt(r, 8).toString());
		cbTinhTrang.setSelectedItem(tblNhanVien.getValueAt(r, 7).toString());
	}
    
    public void timTheoSDT() {
		String sdt = txtTimKiem.getText().trim();

		if (sdt.isEmpty() || sdt.trim() == "") {
			napDuLieuNhanVienTuCSDL(nhanVien_dao.getAllNhanVien());
			xoaTrangNhanVien();
		} else {
			ArrayList<NhanVien> nvList = nhanVien_dao.getTheoSDT(sdt);
			if (nvList.size() > 0) {
				napDuLieuNhanVienTuCSDL(nvList);
				xoaTrangNhanVien();

			} else {
				JOptionPane.showMessageDialog(this, "Không tìm thấy!");
			}
		}

	}
    
    public String phatSinhMaNV(String chucVu) {
    	String prefix = "";
    	if(chucVu.equals("Nhân viên bán hàng")) {
    		prefix = "NV0";
    	}else if (chucVu.equals("Nhân viên quản lý")) {
    		prefix = "NV1";
    	}
    	return prefix + String.format("%02d", modelNV.getRowCount()+ 1);
    }
    
    
    
//   Tài khoản bắt đầu từ đây 
    
    public void napDuLieuTaiKhoanTuCSDL(ArrayList<TaiKhoan> ds) {
    	DefaultTableModel dm = (DefaultTableModel) tblTaiKhoan.getModel();
		dm.getDataVector().removeAllElements();
		for (TaiKhoan tk : ds) {
			modelTK.addRow(new Object[] {tk.getMaTaiKhoan(),tk.getEmail(),tk.getMatKhau(),tk.getTenTaiKhoan(),tk.getNhanVien().getMaNhanVien()});
		}
    }
    
    public void fillFormTK(int r) {
    	txtMaTK.setText(tblTaiKhoan.getValueAt(r, 0).toString());
    	txtEmailTK.setText(tblTaiKhoan.getValueAt(r, 1).toString());
    	txtMatKhau.setText(tblTaiKhoan.getValueAt(r, 2).toString());
    	txtTenTK.setText(tblTaiKhoan.getValueAt(r, 3).toString());
    	cbMaNhanVien.setSelectedItem(tblTaiKhoan.getValueAt(r, 4).toString());
	
	}
    public void napComboBoxMaNhanVien(ArrayList<NhanVien> ds) {
		int n = ds.size();
		String items[] = new String[n];
		int i = 0;
		for (NhanVien nv : ds) {
			items[i] = nv.getMaNhanVien() + "";
			i++;
		}
		cbMaNhanVien.setModel(new DefaultComboBoxModel<String>(items));
	}
    
    private TaiKhoan revertTaiKhoanFromFields() {
    	String maTK ="";
    	String tenTK = txtTenTK.getText().trim();
    	String emailTK = txtEmailTK.getText().trim();
    	String matKhau = txtMatKhau.getText().trim();
    	NhanVien nv = new NhanVien((String) cbMaNhanVien.getSelectedItem());
    	maTK= phatSinhMaTK();
    	TaiKhoan tk = new TaiKhoan(maTK, emailTK, matKhau, tenTK, nv);
    	return tk;
    }
    
    public String phatSinhMaTK() {
    	String prefix = "TK";
    	return prefix + String.format("%03d", modelTK.getRowCount()+ 1);
    }
    
    private void xoaTrangTaiKhoan() {
		txtMaTK.setText("");
		txtTenTK.setText("");
		txtEmail.setText("");
		txtMatKhau.setText("");
		cbMaNhanVien.setSelectedIndex(0);
		txtTenTK.requestFocus();
	}
    
    private void updateTaiKhoan() {
    	int r = tblTaiKhoan.getSelectedRow();
		if (r == -1) {
			JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng để cập nhật thông tin");
		} else {
				String maTK = txtMaTK.getText().trim();
	    		String tenTK = txtTenTK.getText().trim();
	    		String emailTK = txtEmailTK.getText().trim();
	    		String matKhau = txtMatKhau.getText().trim();
	    		NhanVien nv = new NhanVien((String) cbMaNhanVien.getSelectedItem());
				TaiKhoan tkMoi = new TaiKhoan(maTK, emailTK, matKhau, tenTK, nv);
				if (!taiKhoan_dao.capNhat(tkMoi)) {
					System.out.println(tkMoi);
					JOptionPane.showMessageDialog(this, "Lỗi không thể cập nhật");
					tblTaiKhoan.clearSelection();
				} else {
					
					JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thành công");
					napDuLieuTaiKhoanTuCSDL(taiKhoan_dao.getAllTaiKhoan());
				}
		}
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnCapNhatTK;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnTaoMoiTK;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTimTK;
    private javax.swing.JComboBox<String> cbChucVu;
    private javax.swing.JComboBox<String> cbMaNhanVien;
    private javax.swing.JComboBox<String> cbTinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdNgaySinh;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlTaiKhoan;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblTaiKhoan;
    private javax.swing.JTabbedPane tpNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailTK;
    private javax.swing.JTextField txtHoTenNhanVien;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMaTK;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtMessageTK;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenTK;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimTK;
    // End of variables declaration//GEN-END:variables
}
